config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
       controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    mount Sidekiq::Web => '/sidekiq'
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }

    resources :users, only: %i(show)

    resources :fields, only: %i(index show) do
      member do
        get :favorite
        get :unfavorite
      end
    end

    resources :account_activations, only: %i(edit)

    namespace :admin do
      resources :users, only: %i(index destroy)
      resources :booking_fields, only: %i(index update)
      resources :fields, only: %i(new create edit update destroy) do
        member do
          get "status", to: "fields#status"
          get "/dashboard", to: "dashboards#show"
        end
        collection do
          get "/dashboards", to: "dashboards#index"
        end
      end
      resources :vouchers, only: %i(index new create)
    end

    namespace :user do
      resources :users, only: %i(show update edit)
      resources :booking_fields, only: %i(new create pay update) do
        member do
          get :pay
          get :demo_payment
        end
        collection do
          get :export
          get :export_status
          get :export_download
        end
      end
      get "/history", to: "booking_fields#index"
      get "/timeline", to: "activities#index"

      resources :ratings, only: %i(create destroy) do
        resources :comments, only: :create
      end

      resources :fields, only: %i(show) do
        resources :ratings, only: %i(create destroy)
      end
    end

    namespace :api do
      namespace :v1 do
        namespace :user do
            resources :booking_fields, only: %i(new  index create update) do
            end
            resources :fields, only: %i(show) do
              resources :ratings, only: %i(create destroy index)
            end
        end
        resources :fields, only: %i(index create destroy update show) do
          resources :ratings, only: %i(index)
          member do
            get "average_rating"
          end
          member do
            get :status
          end
        end
      end
    end

    root "fields#index"
  end
end

app/views/shared/_calendar.html.erb
<div class="d-flex justify-content-between mb-3">
  <%= link_to I18n.t("calendar.days.today"), path.call(@field, date: Time.zone.today), class: "btn btn-primary" %>
  <div class="d-flex align-items-center">
    <%= link_to "&lt;".html_safe, path.call(@field, date: @date - Settings.calendar.change_week.week), class: "btn btn-secondary mr-2" %>
    <span class="font-weight-bold"><%= month_year_format @start_of_week %></span>
    <%= link_to "&gt;".html_safe, path.call(@field, date: @date + Settings.calendar.change_week.week), class: "btn btn-secondary ml-2" %>
  </div>
</div>

<div class="calendar-legend">
  <h3><%= t "calendar.notes.note" %></h3>
  <ul class="list-unstyled">
    <li>
      <span class="badge booked-3"><%= t "calendar.notes.close" %></span> - <%= t "calendar.notes.close_time" %>
    </li>
    <li>
      <span class="badge booked"><%= t "calendar.notes.open" %></span> - <%= t "calendar.notes.open_time" %>
    </li>
    <li>
      <span class="badge booked-0"><%= t "calendar.notes.pending" %></span> - <%= t "calendar.notes.pending" %>
    </li>
    <li>
      <span class="badge booked-1"><%= t "calendar.notes.approval" %></span> - <%= t "calendar.notes.approval" %>
    </li>
  </ul>
</div>

<div class="calendar">
  <%= days_row %>
  <% @time_slots.each do |time| %>
    <%= time_slot_row time %>
  <% end %>
  <% if @date == Time.zone.today %>
    <div id="current-time-indicator" class="current-time-indicator"></div>
  <% end %>
</div>

app/views/shared/_comment.html.erb
<div class="section bg-transparent">
  <h2><strong><%= t ".comment_text" %></strong></h2>
  <div class="row rating">
     <div id="rating">
        <i class="fa fa-star" data-value="1"></i>
        <i class="fa fa-star" data-value="2"></i>
        <i class="fa fa-star" data-value="3"></i>
        <i class="fa fa-star" data-value="4"></i>
        <i class="fa fa-star" data-value="5"></i>
    </div>
    <input type="hidden" id="rating-value" name="rating" value="0">

    <input
      type="text"
      name="name"
      class="form-control"
      placeholder="Bình luận"
      style="height: 50px"
    />
    <%= link_to t(".publish"), "#", class: "btn btn-success" %>
    <div>
      <h4>...</h4>
      <div class="row comment-container"></div>
      <div class="comment">
        <div class="sub-comment">
          <img
            src= <%= Settings.comment_example_avatar %>
            class="comment-avatar"
            alt="Avatar"
          />
          <div>
            <h5><strong>...</strong></h5>
            <p>...</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if error_object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %>
      <%= pluralize error_object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% error_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_field_form.html.erb
<div class="row g-3">

  <div class="col-md-4 mb-4">
    <%= form.label :grass, t(".grass_type") %> <span class="text-danger">(*)</span>
    <%= form.select :grass, options_for_select([[t(".grass_types.natural"), "natural"], [t(".grass_types.artificial"), "artificial"]]), class: "form-control", required: true %>
  </div>

  <div class="col-md-4 mb-4">
    <%= form.label :open_time, t(".open_time") %> <span class="text-danger">(*)</span>
    <%= form.time_select :open_time, minute_step: Settings.field.minute_step, class: "form-control", required: true %>
  </div>

  <div class="col-md-4 mb-4">
    <%= form.label :close_time, t(".close_time") %> <span class="text-danger">(*)</span>
    <%= form.time_select :close_time, minute_step: Settings.field.minute_step, class: "form-control", required: true %>
  </div>

  <div class="col-md-6 mb-4">
    <label style="display: inline-flex; align-items: center;">
      <%= t ".name" %>
      <span class="text-danger" style="margin-left: 5px;">(*)</span>
    </label>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="col-md-6 mb-4">
    <div class="field_with_errors">
      <label style="display: inline-flex; align-items: center;">
        <%= t ".price" %>
        <span class="text-danger" style="margin-left: 5px;">(*)</span>
      </label>
      <%= form.number_field :price, step: Settings.field.price_step, class: "form-control", required: true %>
    </div>
  </div>

  <div class="col-md-12 mb-4">
    <%= form.label :address, t(".address") %> <span class="text-danger">(*)</span>
    <%= form.text_area :address, class: "form-control", rows: 3, required: true %>
  </div>

  <div class="col-md-12 text-right mt-4">
    <%= form.submit t(".submit"), class: "btn btn-primary", required: true %>
  </div>

  <div class="col-md-12 mb-4">
    <%= form.label :images, t(".images") %>
    <%= form.file_field :images, multiple: true, accept: Settings.image.file_type, class: "form-control" %>
    <div id="image-preview-container"></div>
    <%= form.hidden_field :image_storage, id: "image-storage-input" %>
    <%= form.hidden_field :image_delete, id: "image-delete-input" %>
  </div>
</div>

app/views/shared/_field_infor.html.erb
<div>
  <div class="detail-info">
    <h2 class="row field-detail-name">
      <%= @field.name %> <br/>
      <span class="rating-star">
        <%= display_rating(@average_rating) %>
      </span>
    </h2>
    <div class="row">
      <div class="col-md-3">
        <%= link_to t(".back_to_prev_page"), fields_path, class: "btn btn-success" %>
        <%= link_to t(".booking_field"), new_user_booking_field_path(field_id: @field.id) , class: "btn btn-success" %>
      </div>
    </div>
  </div>
  <div class="detail-img">
    <%= image_tag @field.images.first if @field.images.attached? %>
  </div>
</div>

<div class="section bg-transparent row mb-5 section-field-detail dflex">
  <div class="col-md-6 field-description">
    <div id="favorite_button_<%= @field.id %>">
      <%= render_favorite_button_if_user @field %>
    </div>
    <h2 class=""><strong><%= t ".description" %></strong></h2>
    <div class="row">
      <div class="col-md-6 description-field">
        <p>
          <strong><%= t ".rating" %> </strong><%= @average_rating.present? ? @average_rating.round(1) : t(".no_rating_yet") %>
        </p>
        <p>
          <strong><%= t ".price" %> </strong><%= @field.price %> <%= t(".currency") %>
        </p>
        <p>
          <strong><%= t ".grass" %> </strong> <%= @field.grass %>
        </p>
        <p>
          <strong><%= t ".capacity" %> </strong> <%= @field.capacity %> <%= t ".people" %>
        </p>
      </div>
      <div class="col-md-6 text-start">
        <p>
          <strong><%= t ".open_time" %> </strong> <%= @field.open_time.strftime Settings.format_date %>
        </p>
        <p>
          <strong><%= t ".close_time" %> </strong> <%= @field.close_time.strftime Settings.format_date %>
        </p>
        <p>
          <strong><%= t ".block_time" %> </strong> <%= @field.block_time %> <%= t(".hour") %>
        </p>
        <p>
          <strong><%= t ".address" %> </strong> <%= @field.address %>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-6 g-4 list-field">
    <%== pagy_bootstrap_nav @pagy %>
    <% @images.each do |image| %>
      <%= image_tag(image, class: "d-block w-100 field_infor_image") %>
    <% end %>
  </div>
</div>

app/views/shared/_toast.html.erb
<% flash.each do |message_type, message| %>
  <div class="toast-container position-fixed top-0 end-0 p-3" style="z-index: 1050;">
    <% if message_type == "success" %>
      <%= render "shared/toast_success", msg: message %>
    <% elsif message_type == "alert" %>
      <%= render "shared/toast_alert", msg: message %>
    <% elsif message_type == "danger" %>
      <% if message.is_a?(Array) %>
        <% message.each do |msg| %>
          <%= render "shared/toast_error", msg: msg %>
        <% end %>
      <% else %>
        <%= render "shared/toast_error", msg: message %>
      <% end %>
    <% elsif message_type == "info" %>
      <%= render "shared/toast_info", msg: message %>
    <% end %>
  </div>
<% end %>

app/views/shared/_toast_alert.html.erb
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
  <div class="toast-header bg-danger text-light">
    <strong class="me-auto"><%= I18n.t("shared.toast.alert") %></strong>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body bg-danger text-light">
    <%= msg %>
  </div>
</div>

app/views/shared/_toast_error.html.erb
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
  <div class="toast-header bg-danger text-light">
    <strong class="me-auto"><%= I18n.t("shared.toast.error") %></strong>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body bg-danger text-light">
    <%= msg %>
  </div>
</div>

app/views/shared/_toast_info.html.erb
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
  <div class="toast-header bg-info text-light">
    <strong class="me-auto"><%= I18n.t("shared.toast.info") %></strong>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body bg-info text-light">
    <%= msg %>
  </div>
</div>

app/views/shared/_toast_success.html.erb
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
  <div class="toast-header bg-success text-light">
    <strong class="me-auto"><%= I18n.t("shared.toast.success") %></strong>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body bg-success text-light">
    <%= msg %>
  </div>
</div>