config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
       controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    mount Sidekiq::Web => '/sidekiq'
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }

    resources :users, only: %i(show)

    resources :fields, only: %i(index show) do
      member do
        get :favorite
        get :unfavorite
      end
    end

    resources :account_activations, only: %i(edit)

    namespace :admin do
      resources :users, only: %i(index destroy)
      resources :booking_fields, only: %i(index update)
      resources :fields, only: %i(new create edit update destroy) do
        member do
          get "status", to: "fields#status"
          get "/dashboard", to: "dashboards#show"
        end
        collection do
          get "/dashboards", to: "dashboards#index"
        end
      end
      resources :vouchers, only: %i(index new create)
    end

    namespace :user do
      resources :users, only: %i(show update edit)
      resources :booking_fields, only: %i(new create pay update) do
        member do
          get :pay
          get :demo_payment
        end
        collection do
          get :export
          get :export_status
          get :export_download
        end
      end
      get "/history", to: "booking_fields#index"
      get "/timeline", to: "activities#index"

      resources :ratings, only: %i(create destroy) do
        resources :comments, only: :create
      end

      resources :fields, only: %i(show) do
        resources :ratings, only: %i(create destroy)
      end
    end

    namespace :api do
      namespace :v1 do
        namespace :user do
            resources :booking_fields, only: %i(new  index create update) do
            end
            resources :fields, only: %i(show) do
              resources :ratings, only: %i(create destroy index)
            end
        end
        resources :fields, only: %i(index create destroy update show) do
          resources :ratings, only: %i(index)
          member do
            get "average_rating"
          end
          member do
            get :status
          end
        end
      end
    end

    root "fields#index"
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  authorize_resource class: false

  before_action :find_field, only: %i(show)
  before_action :find_params_statistic
  def index
    @q = BookingField.ransack(params[:q])
    @filtered_bookings = @q.result.includes(:field)

    return unless validate_date_range

    @revenue_data = @filtered_bookings
                    .grouped_revenue(@analysis_type,
                                     @date_from, @date_to)

    @revenue_by_capacity = @filtered_bookings.revenue_by_capacity
    @revenue_by_grass = @filtered_bookings.revenue_by_grass
  end

  def show
    @q = @field.booking_fields.ransack(params[:q])
    @booking_fields = @q.result(distinct: true)
    return unless validate_date_range

    @revenue_field_data = @booking_fields
                          .grouped_revenue(@analysis_type,
                                           @date_from, @date_to)
  end

  private

  def find_field
    @field = Field.find_by id: params[:id]
    return if @field.present?

    flash[:danger] = t "admin.fields.messages.error_field_not_found"
    redirect_to fields_path
  end

  def find_params_statistic
    @date_from = find_date_from
    @date_to = find_date_to
    @analysis_type = find_analysis_type
  end

  def find_date_from
    if params.dig(:q, :date_gteq).present?
      Date.parse(params[:q][:date_gteq])
    else
      Settings.chartkick.date_from_default.month.ago.to_date
    end
  end

  def find_date_to
    if params.dig(:q,
                  :date_lteq).present?
      Date.parse(params.dig(:q, :date_lteq))
    else
      Time.zone.today
    end
  end

  def find_analysis_type
    params[:analysis_type].presence || :month
  end

  def validate_date_range
    return true unless @date_to < @date_from

    flash[:danger] = t "admin.dashboards.validate_date"
    false
  end
end

app/views/admin/dashboards/_filter_index.html.erb
<%= search_form_for @q, url: dashboards_admin_fields_path, method: :get, class: "filter-form" do |f| %>
  <div class="row g-3 mb-3">
    <div class="col-md-4">
      <%= f.label :date_gteq, t("admin.dashboards.filter.date.from") %>
      <%= f.date_field :date_gteq, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= f.label :date_lteq, t("admin.dashboards.filter.date.to") %>
      <%= f.date_field :date_lteq, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= label_tag :analysis_type, t("admin.dashboards.filter.analysis_type") %>
      <%= select_tag :analysis_type,
                                options_for_select([
                                  [t("admin.dashboards.filter.week"), :week],
                                  [t("admin.dashboards.filter.month"), :month],
                                  [t("admin.dashboards.filter.day"), :day]],
                                  params[:analysis_type]), class: "form-control" %>
    </div>
  </div>

  <div class="row g-3 mb-3">
    <div class="col-md-6">
      <%= f.label :field_capacity_eq, t("admin.dashboards.filter.capacity.capacity_type") %>
      <%= f.select :field_capacity_eq,
                            options_for_select([
                              [t("admin.dashboards.filter.capacity.all"), ""],
                              [t("admin.dashboards.filter.capacity.five"), 5],
                              [t("admin.dashboards.filter.capacity.seven"), 7],
                              [t("admin.dashboards.filter.capacity.eleven"), 11]],
                              ), class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= f.label :field_grass_eq, t("admin.dashboards.filter.grass.grass_type") %>
      <%= f.select :field_grass_eq,
                            options_for_select([
                              [t("admin.dashboards.filter.grass.all"), ""],
                              [t("admin.dashboards.filter.grass.natural"), 0],
                              [t("admin.dashboards.filter.grass.artificial"), 1]],
                              ), class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-end">
      <%= f.submit "Filter", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/dashboards/_filter_show.html.erb
<%= search_form_for @q, url: dashboard_admin_field_path, method: :get, class: "filter-form" do |f| %>
  <div class="row">
    <div class="col-md-3">
      <%= f.label :date_gteq, t("admin.dashboards.filter.date.from") %>
      <%= f.date_field :date_gteq, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :date_lteq, t("admin.dashboards.filter.date.to") %>
      <%= f.date_field :date_lteq, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= label_tag :analysis_type,t("admin.dashboards.filter.analysis_type") %>
      <%= select_tag :analysis_type,
                                 options_for_select([
                                  [t("admin.dashboards.filter.week"), :week],
                                  [t("admin.dashboards.filter.month"), :month],
                                  [t("admin.dashboards.filter.day"), :day]],
                                  params[:analysis_type]), class: "form-control" %>
    </div>
    <div class="col-md-3 align-self-end">
      <%= f.submit "Filter", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/dashboards/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<%= render "filter_index" %>

<div class="charts">
  <div class="row">
    <div>
      <%= t ".revenue" %>
      <strong class="ml-2 font-semibold text-lg">
        <%= @filtered_bookings.sum(:total).round(Settings.chartkick.round) %>
      </strong>
      <strong class="ml-2 font-semibold text-lg">
        <%= t ".currency" %>
      </strong>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= line_chart @revenue_data, 
                    title: t(".revenue_over_time"), 
                    xtitle: t(".title_x_date"), 
                    ytitle: t(".title_y_revenue"),
                    empty: t(".no_appropiate_result")
      %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-6">
      <%= pie_chart @revenue_by_capacity,
                    title: t(".revenue_by_capacity"),
                    height: "300px",
                    empty: t(".no_appropiate_result"),
                    donut: true,
                    label: true
      %>
    </div>
    <div class="col-md-6">
      <%= pie_chart @revenue_by_grass, 
                    title: t(".revenue_by_grass"),
                    height: "300px",
                    empty: t(".no_appropiate_result"),
                    donut: true,
                    label: true 
      %>
    </div>
  </div>
</div>

app/views/admin/dashboards/show.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title", field_name: @field.name %></h1>

<%= render "filter_show" %>

<div class="row padding-top-10">
  <div>
    <%= t ".total" %>
    <strong class="ml-2 font-semibold text-lg">
      <%= @booking_fields.sum(:total).round(Settings.chartkick.round) %>
    </strong>
    <strong class="ml-2 font-semibold text-lg">
        <%= t ".currency" %>
    </strong>
  </div>
</div>
<div class="row">
  <%= line_chart @revenue_field_data, 
                  title: t(".revenue_over_time"), 
                  xtitle: t(".title_x_date"), 
                  ytitle: t(".title_y_revenue"),
                  empty: t(".no_appropiate_result") 
  %>
</div>