config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
       controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    mount Sidekiq::Web => '/sidekiq'
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      unlocks: "users/unlocks"
    }

    resources :users, only: %i(show)

    resources :fields, only: %i(index show) do
      member do
        get :favorite
        get :unfavorite
      end
    end

    resources :account_activations, only: %i(edit)

    namespace :admin do
      resources :users, only: %i(index destroy)
      resources :booking_fields, only: %i(index update)
      resources :fields, only: %i(new create edit update destroy) do
        member do
          get "status", to: "fields#status"
          get "/dashboard", to: "dashboards#show"
        end
        collection do
          get "/dashboards", to: "dashboards#index"
        end
      end
      resources :vouchers, only: %i(index new create)
    end

    namespace :user do
      resources :users, only: %i(show update edit)
      resources :booking_fields, only: %i(new create pay update) do
        member do
          get :pay
          get :demo_payment
        end
        collection do
          get :export
          get :export_status
          get :export_download
        end
      end
      get "/history", to: "booking_fields#index"
      get "/timeline", to: "activities#index"

      resources :ratings, only: %i(create destroy) do
        resources :comments, only: :create
      end

      resources :fields, only: %i(show) do
        resources :ratings, only: %i(create destroy)
      end
    end

    namespace :api do
      namespace :v1 do
        namespace :user do
            resources :booking_fields, only: %i(new  index create update) do
            end
            resources :fields, only: %i(show) do
              resources :ratings, only: %i(create destroy index)
            end
        end
        resources :fields, only: %i(index create destroy update show) do
          resources :ratings, only: %i(index)
          member do
            get "average_rating"
          end
          member do
            get :status
          end
        end
      end
    end

    root "fields#index"
  end
end

app/models/field.rb
class Field < ApplicationRecord
  PERMITTED_ATTRIBUTES = [:name,
  :price,
  :grass,
  :capacity,
  :open_time,
  :close_time,
  :address].freeze

  enum grass: {natural: 0, artificial: 1}

  scope :filter_by_name, lambda {|name|
                           where("name LIKE ?", "%#{name}%") if name.present?
                         }
  scope :filter_by_grass, lambda {|grass_type|
                            where(grass: grass_type) if grass_type.present?
                          }
  scope :filter_by_capacity, lambda {|capacity_type|
                               if capacity_type.present?
                                 where(capacity: capacity_type)
                               end
                             }
  scope :sort_by_price, lambda {|direction|
                          order(price: direction) if direction.present?
                        }
  scope :with_ave_rate, lambda {left_joins(:ratings) # rubocop:disable Layout/MultilineBlockLayout
    .select("fields.*, AVG(ratings.rating) as average_rating")
    .group("fields.id")
                        }

  scope :favorited_by, lambda {|user, favorites_param|
    return unless favorites_param.present? && user.present?

    joins(:favorites).where(favorites: {user_id: user.id})
  }

  ransacker :average_rating do |_parent|
    Arel.sql('( SELECT AVG(ratings.rating)
                FROM ratings
                WHERE ratings.field_id = fields.id
              )')
  end

  def self.ransackable_attributes _auth_object = nil
    %w(name price grass capacity average_rating)
  end

  def self.ransackable_scopes _auth_object = nil
    %i(with_ave_rate)
  end

  def self.ransackable_associations _auth_object = nil
    %w(ratings)
  end

  has_many_attached :images
  has_many :booking_fields, dependent: :destroy
  has_many :users, through: :booking_fields
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :capacity, presence: true, inclusion: {in: [5, 7, 11]}
  validates :price,
            presence: {message: I18n.t("fields.messages.price.blank")}
  validate :validate_price_range
  validate :validate_name_length
  validate :validate_address_length

  private

  def validate_price_range
    if price.present? &&
       (price < Settings.field.price_min || price > Settings.field.price_max)
      errors.add(:price,
                 I18n.t("fields.messages.price.invalid_range",
                        min: Settings.field.price_min,
                        max: Settings.field.price_max))
    end
  end

  def validate_name_length
    if name.blank?
      add_name_blank_error
    else
      check_name_length
    end
  end

  def add_name_blank_error
    errors.add(:name, I18n.t("fields.messages.name.blank"))
  end

  def check_name_length
    if name.length < Settings.field.name_min_len
      errors.add(:name, I18n.t("fields.messages.name.too_short",
                               count: Settings.field.name_min_len))
    elsif name.length > Settings.field.name_max_len
      errors.add(:name, I18n.t("fields.messages.name.too_long",
                               count: Settings.field.name_max_len))
    end
  end

  def validate_address_length
    if address.blank?
      add_address_blank_error
    else
      check_address_length
    end
  end

  def add_address_blank_error
    errors.add(:address, I18n.t("fields.messages.address.blank"))
  end

  def check_address_length
    if address.length < Settings.field.address_min_len
      errors.add(:address, I18n.t("fields.messages.address.too_short",
                                  min: Settings.field.address_min_len))
    elsif address.length > Settings.field.address_max_len
      errors.add(:address, I18n.t("fields.messages.address.too_long",
                                  max: Settings.field.address_max_len))
    end
  end
end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < Admin::BaseController
  before_action :set_field, except: %i(new create)
  before_action :set_date, only: %i(status)

  def status; end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new field_params

    if @field.save
      attach_images if params[:field][:image_storage].present?
      flash[:success] = t ".success_message"
      redirect_to new_admin_field_path, status: :see_other
    else
      flash.now[:danger] = t ".failure_message"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @existing_images = @field.images.map do |image|
      {url: url_for(image), blob_id: image.blob.id}
    end
  end

  def update
    if @field.update field_params
      process_attachments
      flash[:success] = t ".success_message"
      redirect_to status_admin_field_path @field, status: :see_other
    else
      flash.now[:danger] = t ".failure_message"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    unless can_destroy_field?
      flash[:danger] = t ".cannot_delete"
      return redirect_to admin_field_path @field, status: :see_other
    end

    if @field.destroy
      flash[:success] = t ".success_message"
      redirect_to fields_path, status: :see_other
    else
      flash[:danger] = t ".failure_message"
      redirect_to admin_field_path @field, status: :see_other
    end
  end

  private

  def process_attachments
    attach_images if params[:field][:image_storage].present?
    remove_images if params[:field][:image_delete].present?
  end

  def field_params
    params.require(:field).permit(Field::PERMITTED_ATTRIBUTES)
  end

  def can_destroy_field?
    @field.booking_fields
          .future_bookings
          .pending_or_approved
          .none?
  end

  def set_field
    @field = Field.find_by id: params[:id]
    return if @field.present?

    flash[:danger] = t ".messages.error_field_not_found"
    redirect_to fields_path
  end

  def set_date
    @date = if params[:date].present?
              Date.parse params[:date].to_s
            else
              Time.zone.today
            end
  end

  def attach_images
    image_data = JSON.parse params[:field][:image_storage]
    image_data.each do |base64_image|
      decoded_image = Base64.decode64 base64_image.split(",").last
      filename = "field_image_#{SecureRandom.hex}.png"
      tempfile = Tempfile.new filename
      tempfile.binmode
      tempfile.write decoded_image
      tempfile.rewind

      @field.images.attach(io: tempfile, filename:)
      tempfile.close
      tempfile.unlink
    end
  end

  def remove_images
    image_data = JSON.parse params[:field][:image_delete]
    image_data.each do |blob_id|
      image = @field.images.find_by(blob_id:)
      image.purge if image.present?
    end
  end
end

app/controllers/api/v1/fields_controller.rb
class Api::V1::FieldsController < ApplicationController
  protect_from_forgery with: :null_session

  include Authenticable

  skip_before_action :authenticate_user!, only: %i(index average_rating show)
  before_action :authenticate_admin!, only: %i(create update destroy status)
  before_action :set_field, only: %i(destroy update average_rating show status)

  def show
    images = @field.images.map do |image|
      {
        id: image.id,
        url: rails_blob_url(image, only_path: true)
      }
    end

    bookings = @field.booking_fields.map do |booking|
      {
        id: booking.id,
        date: booking.date,
        start_time: booking.start_time,
        end_time: booking.end_time,
        status: booking.status
      }
    end

    render json: {
      field: @field.as_json.merge(images:, bookings:),
      average_rating: avg_rating
    }, status: :ok
  end

  def status
    bookings = @field.booking_fields.map do |booking|
      {
        id: booking.id,
        user_id: booking.user_id,
        date: booking.date,
        start_time: booking.start_time,
        end_time: booking.end_time,
        status: booking.status,
        field_id: booking.field_id,
        total: booking.total,
        paymentStatus: booking.paymentStatus
      }
    end

    render json: {
      field: @field.as_json.merge(bookings:),
      average_rating: avg_rating
    }, status: :ok
  end

  def index
    @q = Field.ransack params[:q]
    @fields = @q.result(distinct: true).with_ave_rate

    render json: @fields, each_serializer: FieldSerializer,
           current_user: @current_user, status: :ok
  end

  def create
    @field = Field.new field_params

    if @field.save
      attach_images if params[:images].present?
      render json: @field, serializer: FieldSerializer, status: :created
    else
      render json: {errors: @field.errors.full_messages},
             status: :unprocessable_entity
    end
  end

  def destroy
    unless can_destroy_field?
      render json: {message: I18n.t("api.v1.field.delete.unauthorized")},
             status: :ok
      return
    end

    if @field.destroy
      render json: {message: I18n.t("api.v1.field.delete.success")}, status: :ok
    else
      render json: {error: I18n.t("api.v1.field.delete.failure")},
             status: :unprocessable_entity
    end
  end

  def update
    if @field.update field_params
      replace_images if params[:field][:images].present?
      render json: @field, serializer: FieldSerializer, status: :ok
    else
      render json: {errors: @field.errors.full_messages},
             status: :unprocessable_entity
    end
  end

  def average_rating
    render json: {average_rating: avg_rating}, status: :ok
  end

  private

  def set_field
    @field = Field.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render json: {error: I18n.t("api.v1.field.not_found")}, status: :not_found
  end

  def can_destroy_field?
    @field.booking_fields
          .future_bookings
          .pending_or_approved
          .none?
  end

  def field_params
    params.require(:field).permit(Field::PERMITTED_ATTRIBUTES + [images: []])
  end

  def attach_images
    return if params[:field][:images].blank?

    params[:field][:images].each do |image|
      @field.images.attach image
    end
  end

  def replace_images
    @field.images.purge

    params[:field][:images].each do |image|
      @field.images.attach image
    end
  end

  def avg_rating
    avg_rating = @field.ratings.average(:rating).to_f
    avg_rating.nan? ? 0 : avg_rating
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :find_field, only: %i(show favorite unfavorite)
  before_action :authorize_favorite, only: %i(favorite)
  before_action :authorize_unfavorite, only: %i(unfavorite)

  def index
    @q = Field.ransack(params[:q])
    @fields = @q.result(distinct: true).with_ave_rate
    @pagy, @fields = pagy(@fields, limit: Settings.field_in_field_list)
  end

  def show
    @rating = @field.ratings.build comment: Comment.new
    @average_rating = @field.ratings.average(:rating).to_f
    @images = @field.images

    @pagy, @images = pagy @images, limit: Settings.image_field_in_field_detail
  end

  def favorite
    favorite = current_user.favorites.new favoritable: @field
    if favorite.save
      flash[:success] = t ".favorites.favorite_added"
    else
      flash[:danger] = t ".favorites.favorite_failed"
      redirect_to fields_path and return
    end

    respond_to_format
  end

  def unfavorite
    favorite = find_favorite

    if favorite.present? && destroy_favorite(favorite)
      flash[:success] = t ".favorites.favorite_removed"
    else
      handle_unfavorite_error
      return
    end

    respond_to_format
  end

  private

  def find_field
    @field = Field.find_by id: params[:id]
    return if @field

    flash[:danger] = t ".favorites.field_not_found"
    redirect_to fields_path
  end

  def filter
    @fields = @fields
              .filter_by_name(params[:name])
              .filter_by_grass(params[:grass])
              .filter_by_capacity(params[:capacity])
              .sort_by_price(params[:price])
              .favorited_by(current_user, params[:favorites])
  end

  def find_favorite
    current_user.favorites.find_by favoritable: @field
  end

  def destroy_favorite favorite
    favorite&.destroy
  end

  def handle_unfavorite_error
    flash[:danger] = t ".favorites.favorite_remove_failed"
    redirect_to fields_path and return
  end

  def respond_to_format
    respond_to do |format|
      format.turbo_stream
      format.html{redirect_back fallback_location: field_path(@field)}
    end
  end

  def authorize_favorite
    authorize! :favorite, @field
  rescue CanCan::AccessDenied
    flash[:alert] = I18n.t("authenticate.not_allowed")
    redirect_to fields_path
  end

  def authorize_unfavorite
    authorize! :unfavorite, @field
  rescue CanCan::AccessDenied
    flash[:alert] = I18n.t("authenticate.not_allowed")
    redirect_to fields_path
  end
end

app/helpers/admin/fields_helper.rb
module Admin::FieldsHelper
  def render_field_status_calendar field, selected_date
    render_calendar(
      field,
      selected_date,
      ->(f, d){status_admin_field_path(f, date: d)}
    )
  end

  def render_existing_images_script existing_images
    return unless existing_images.any?

    content_tag :script do
      "var existingImages = #{existing_images.to_json};".html_safe # rubocop:disable Rails/OutputSafety
    end
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
  def display_rating rating
    full_stars = rating.to_i
    half_star = (rating - full_stars) >= 0.5 ? 1 : 0
    empty_stars = 5 - full_stars - half_star

    content_tag :span, class: "rating-star" do
      (full_stars.times.map{content_tag(:i, "", class: "fa fa-star")} +
      (if half_star.positive?
         [content_tag(:i, "",
                      class: "fa fa-star-half")]
       else
         []
       end) +
      empty_stars.times.map do
        content_tag(:i, "", class: "fa fa-star empty-star")
      end).join.html_safe # rubocop:disable Rails/OutputSafety
    end
  end

  def field_link field
    if current_user&.admin?
      status_admin_field_path field
    else
      field_path field
    end
  end

  def render_create_field_button
    return unless current_user&.admin?

    link_to I18n.t("fields.create.create_field_button"), new_admin_field_path,
            class: "btn btn-success filter-fields-button"
  end

  def render_favorite_button_if_user field
    return unless current_user&.user?

    content_tag :div, id: "favorite_button_#{field.id}" do
      render "favorite_button", field:
    end
  end
end

app/views/fields/_favorite_button.html.erb
<% if current_user.favorited_fields.include?(@field) %>
  <%= link_to unfavorite_field_path(@field), method: :delete, remote: true, class: "btn btn-danger text-white rounded-pill w-50 d-flex align-items-center justify-content-center" do %>
    <i class="fa-solid fa-heart me-2"></i>
    <span><%= I18n.t("fields.favorites.unfavorite") %></span>
  <% end %>
<% else %>
  <%= link_to favorite_field_path(@field), method: :post, remote: true, class: "btn btn-primary text-white rounded-pill w-50 d-flex align-items-center justify-content-center" do %>
    <i class="fa-regular fa-heart me-2"></i>
    <span><%= I18n.t("fields.favorites.favorite") %></span>
  <% end %>
<% end %>

app/views/fields/_field.html.erb
<div class="col-md-4">
  <div class="card h-100 shadow-sm border-0 card-field">
    <%= image_tag field.images.first, class: "card-img-top fixed-img" if field.images.attached? %>
    <div class="card-body">
      <h5 class="card-title text-primary">
        <%= link_to field.name, field_link(field) %>
      </h5>
      <p class="card-text">
        <strong><%= t "fields.field_detail.rating" %></strong>
          <%= field.average_rating.present? ? field.average_rating.round(1) : t("fields.field_detail.no_rating_yet") %><br />
        <strong><%= t "fields.field_detail.price" %></strong>
          <%= number_to_currency(field.price, unit: t("fields.field_detail.currency")) %><br />
        <strong><%= t "fields.field_detail.grass" %></strong>
          <%= field.grass == "artificial" ? t("fields.field_detail.artificial") : t("fields.field_detail.natural") %><br/>
        <strong><%= t "fields.field_detail.address" %></strong>
          <%= field.address %>
      </p>
    </div>

    <div class="card-footer bg-transparent border-0 text-center">
      <%= link_to t("fields.field_detail.view_detail"), field_path(field), class: "btn btn-success view-detail-btn w-100" %>
    </div>
  </div>
</div>

app/views/fields/create.turbo_stream.erb
<%= turbo_stream.replace "favorite_button_#{@field.id}", partial: "fields/favorite_button", locals: { field: @field } %>

app/views/fields/destroy.turbo_stream.erb
<%= turbo_stream.replace "favorite_button_#{@field.id}", partial: "fields/favorite_button", locals: { field: @field } %>

app/views/fields/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4"><%= t ".soccer_field_title" %></h1>
  <%= search_form_for @q, url: fields_path, method: :post, local: true do |f| %>
    <div class="row g-3 filter-margin">
      <div class="col-md-12">
        <%= f.label :name_cont, t(".search_by_name") %>
        <%= f.text_field :name_cont, class: "form-control", placeholder: t(".enter_field_name") %>
      </div>
    </div>
    <div class="row g-3 filter-margin">
      <div class="col-md-3">
        <%= f.label :price_gteq, t(".price.price_placeholder") %>
        <%= f.select :s, options_for_select([
                              [t(".price.all"), ""],
                              [t(".price.desc"), "price desc"],
                              [t(".price.asc"), "price asc"]],
                              ), class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= f.label :grass_eq, t(".grass.grass_type") %>
        <%= f.select :grass_eq, options_for_select([
                              [t(".grass.all"), ""],
                              [t(".grass.natural"), 0],
                              [t(".grass.artificial"), 1]],
                              ), class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= f.label :capacity_eq, t(".capacity.capacity_type") %>
        <%= f.select :capacity_eq, options_for_select([
                              [t(".capacity.all"), ""],
                              [t(".capacity.five"), 5],
                              [t(".capacity.seven"), 7],
                              [t(".capacity.eleven"), 11]],
                              ), class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= f.label :average_rating_gteq, t(".rating.rating_placeholder") %>
        <%= f.select :s, options_for_select([
                            [t(".rating.all"), ""],
                            [t(".rating.desc"), "average_rating desc"],
                            [t(".rating.asc"), "average_rating asc"]],
                            ), class: "form-control" %>
      </div>
    </div>
    <div class="row g-3">
      <div class="col-md-12">
        <%= submit_tag t(".submit_button"), class: "btn btn-success filter-fields-button" %>
        <%= render_create_field_button %>
      </div>
    </div>
  <% end %>

  <%== pagy_bootstrap_nav @pagy %>
  <div class="row g-4 list-field">
    <%= render @fields %>
  </div>
</div>

app/views/fields/show.html.erb
<div class="field-container">
  <%= render "shared/field_infor" %>
  <div class="section bg-transparent">
    <h2><strong><%= t ".comment_text" %></strong></h2>
    <%= render "user/ratings/review" %>
  </div>
</div>